---
name: Build ISOs

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - live
  #   paths:
  #     - './.github/workflows/config/iso.toml'
  #     - './.github/workflows/config/image.toml'
  #     - './.github/workflows/iso-hardened '

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false      
      matrix:
        image:
          - silverblue-main-hardened
          - silverblue-nvidia-hardened 
          - silverblue-nvidia-open-hardened 
          - kinoite-main-hardened 
          - kinoite-nvidia-hardened 
          - kinoite-nvidia-open-hardened 
          - sericea-main-hardened 
          - sericea-nvidia-hardened 
          - sericea-nvidia-open-hardened 
          - cosmic-main-hardened 
          - cosmic-nvidia-hardened 
          - cosmic-nvidia-open-hardened 
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set target image
        shell: bash
        run: sed -i 's/TARGETIMAGE/${{ matrix.image }}/g' ./.github/workflows/config/iso.toml

      - name: Build ISO
        id: iso_build
        uses: secureblue/bootc-image-builder-action@b98784c42327746e107a6a753b64f44823bdbf2f # main
        with:
          use-librepo: true
          config-file: ./.github/workflows/config/iso.toml
          image: "ghcr.io/secureblue/${{ matrix.image }}:latest"

      - name: Rename ISO and sign CHECKSUM
        id: rename
        shell: bash
        env:
          OUTPUT_PATH: ${{ steps.iso_build.outputs.output-path }}
          OUTPUT_DIRECTORY: ${{ steps.iso_build.outputs.output-directory }}
          CHECKSUM_PATH: ${{ steps.iso_build.outputs.checksum-path }}
          IMAGE_NAME: ${{ matrix.image }}
        run: |
          HASH=$(cat $CHECKSUM_PATH)
          ISO_SIZE=$(stat -c %s $OUTPUT_PATH)
          ISO_FILE_NAME=$(basename $OUTPUT_PATH)
          {
            echo "# $ISO_FILE_NAME: $ISO_SIZE bytes"
            echo "SHA256 ($ISO_FILE_NAME) = $HASH"
          } > "$CHECKSUM_PATH"

          echo "${{ secrets.ISO_SIGNING_KEY }}" | gpg --import

          gpg --clearsign -u 26B4463ED8F313BC7E3FBDF9D9223AF0F47B3E41 "$CHECKSUM_PATH"

          # validate signature

          curl -O "http://repo.secureblue.dev/secureblue.gpg"
          gpgv --keyring ./secureblue.gpg "$CHECKSUM_PATH"
          sha256sum --ignore-missing -c "$CHECKSUM_PATH"

          mv $OUTPUT_PATH $OUTPUT_DIRECTORY/$IMAGE_NAME.iso
          mv $CHECKSUM_PATH $OUTPUT_DIRECTORY/$IMAGE_NAME.iso-CHECKSUM

      - name: Sign checksum
        id: Sign
        shell: bash
        run: |

      - name: Upload ISOs and Checksum to Job Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ${{ steps.iso_build.outputs.output-directory }}
          name: ${{ matrix.image }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
      
