# Copyright 2025 The Secureblue Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

name: Build ISOs

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - live
  #   paths:
  #     - './.github/workflows/config/iso.toml'
  #     - './.github/workflows/config/image.toml'
  #     - './.github/workflows/iso-hardened '

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    env:
      kargs: "init_on_alloc=1,init_on_free=1,slab_nomerge,page_alloc.shuffle=1,randomize_kstack_offset=on,vsyscall=none,lockdown=confidentiality,random.trust_cpu=off,random.trust_bootloader=off,iommu=force,intel_iommu=on,iommu.passthrough=0,iommu.strict=1,pti=on,module.sig_enforce=1,mitigations=auto,nosmt,spectre_v2=on,spec_store_bypass_disable=on,l1d_flush=on,l1tf=full,force,kvm-intel.vmentry_l1d_flush=always,loglevel=0"
    strategy:
      fail-fast: false      
      matrix:
        image:
          - silverblue-main-hardened
          - silverblue-nvidia-hardened 
          - silverblue-nvidia-open-hardened 
          - kinoite-main-hardened 
          - kinoite-nvidia-hardened 
          - kinoite-nvidia-open-hardened 
          - sericea-main-hardened 
          - sericea-nvidia-hardened 
          - sericea-nvidia-open-hardened 
          - cosmic-main-hardened 
          - cosmic-nvidia-hardened 
          - cosmic-nvidia-open-hardened 
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Install deps
        shell: bash
        id: install_deps
        run: |
          sudo apt-get install rclone

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: set_kargs
        shell: bash
        id: set_kargs
        run: |
          IMAGE_KARGS="${{ env.kargs }}"
          if [[ "${{ matrix.image }}" == *nvidia* ]]; then
            IMAGE_KARGS="${IMAGE_KARGS},rd.driver.blacklist=nouveau,modprobe.blacklist=nouveau,nvidia-drm.modeset=1,nvidia-drm.fbdev=1"
          fi
          echo "image_kargs=$IMAGE_KARGS" >> $GITHUB_OUTPUT

      - name: set_image_ref
        shell: bash
        id: set_image_ref
        run: |
          sed -i 's|%%REPLACE_IMAGE_REF_TAG%%|ghcr.io/secureblue/${{ matrix.image }}:latest|g' "${{ github.workspace }}/.github/workflows/config/configure_iso_anaconda.sh"

      - name: Build ISO
        id: iso_build
        uses: ublue-os/titanoboa@154e9332aeb79c52789e63eb941f73be99dbaf97 # v0.1
        with:
          image-ref: "ghcr.io/secureblue/${{ matrix.image }}:latest"
          hook-post-rootfs: ${{ github.workspace }}/.github/workflows/config/configure_iso_anaconda.sh
          kargs: ${{ steps.set_kargs.outputs.image_kargs }}

      - name: Rename ISO and sign CHECKSUM
        id: rename
        shell: bash
        env:
          OUTPUT_PATH: ${{ steps.iso_build.outputs.iso-dest }}
          IMAGE_NAME: ${{ matrix.image }}
        run: |
          set -x
          mkdir -p output
          OUTPUT_DIRECTORY="$(realpath output)"
          TARGET_OUTPUT_PATH="${OUTPUT_DIRECTORY}/${IMAGE_NAME}.iso"
          TARGET_CHECKSUM_PATH="${OUTPUT_DIRECTORY}/${IMAGE_NAME}.iso-CHECKSUM"

          
          cd "${OUTPUT_DIRECTORY}"
          mv "${OUTPUT_PATH}" "${IMAGE_NAME}.iso"
          sha256sum "${IMAGE_NAME}.iso" | cut -d' ' -f1 | tee "${TARGET_CHECKSUM_PATH}"

          HASH=$(cat $TARGET_CHECKSUM_PATH)
          ISO_SIZE=$(stat -c %s $TARGET_OUTPUT_PATH)
          ISO_FILE_NAME="${IMAGE_NAME}.iso"
          {
            echo "# $ISO_FILE_NAME: $ISO_SIZE bytes"
            echo "SHA256 ($ISO_FILE_NAME) = $HASH"
          } > "$TARGET_CHECKSUM_PATH"


          echo "CHECKSUM contents"
          cat $TARGET_CHECKSUM_PATH
          echo

          echo "${{ secrets.ISO_SIGNING_KEY }}" | gpg --import

          echo "Signing the ISO"
          gpg --clearsign -u 26B4463ED8F313BC7E3FBDF9D9223AF0F47B3E41 "${IMAGE_NAME}.iso-CHECKSUM"
          mv "${IMAGE_NAME}.iso-CHECKSUM.asc" "${IMAGE_NAME}.iso-CHECKSUM"

          echo "Signed CHECKSUM contents"
          cat "${IMAGE_NAME}.iso-CHECKSUM"
          echo

          # validate signature
          curl -O "https://repo.secureblue.dev/secureblue.gpg"
          gpg --no-default-keyring --keyring ./secureblue-keyring.gpg --import secureblue.gpg

          if ! gpgv --keyring ./secureblue-keyring.gpg "${IMAGE_NAME}.iso-CHECKSUM"; then
              echo "CHECKSUM signature verification FAILED! Exiting..."
              exit 1
          fi

          if ! sha256sum --ignore-missing -c "${IMAGE_NAME}.iso-CHECKSUM"; then
              echo "CHECKSUM verification FAILED! Exiting..."
              exit 1
          fi

          rm ./secureblue-keyring.gpg~
          rm secureblue.gpg
          
          cd -
          echo "output_directory=$OUTPUT_DIRECTORY" >> "${GITHUB_OUTPUT}"

      - name: Upload ISO and Checksum to Job Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ${{ steps.rename.outputs.output_directory }}
          name: ${{ matrix.image }}
          if-no-files-found: error
          retention-days: 20
          compression-level: 0
          overwrite: true

      - name: Upload ISO and checksum to R2 to ISOS Bucket
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.ISOS_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.ISOS_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.ISOS_ENDPOINT }}
          SOURCE_DIR: .
        run: |
          rclone copy "${{ steps.rename.outputs.output_directory }}" R2:isos 
      
