name: run-tests
on:
  pull_request:
    branches:
      - live
    paths-ignore:
      - "**.md"
  workflow_dispatch: # allow manually triggering 
jobs:
  run_tests:
    runs-on: ubuntu-24.04
    name: Install Bats and run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@2104b40bb7b6c2d5110b23a26b0bf265ab8027db #v3.0.0
        with:
          support-path: ${{ github.workspace }}/.github/workflows/test-common/bats-support
          assert-path: ${{ github.workspace }}/.github/workflows/test-common/bats-assert
          detik-install: false
      
      - name: Install just
        run: |          
          sudo apt-get install just

      - name: Run tests
        shell: bash
        env:
          INSTALL_SCRIPT: install/install_secureblue.sh
        run: |
          cd 
          export BATS_LIBS_BASEDIR=./.github/workflows/test-common && bats --timing --trace --verbose-run -r .github/workflows/tests